name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  manage-release:
    name: 'Manage Release'
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: go
          package-name: exiledb

  build:
    name: "Build"
    needs: manage-release
    if: needs.manage-release.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            name: linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            name: linux-arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            name: windows-amd64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            name: darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            name: darwin-arm64
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          if [ "${{ matrix.goarch }}" = "arm64" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
            echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          fi

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          output_name="exiledb-${{ matrix.name }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          go build -o "${output_name}" ./cmd/exiledb

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.manage-release.outputs.tag_name }}
          files: exiledb-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}
